apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazorintapp1
  labels:
    app: blazorintapp1
    kubernetes.azure.com/generator: devhub
  namespace: blazorintapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blazorintapp1
  template:
    metadata:
      labels:
        app: blazorintapp1
    spec:
      containers:
        - name: blazorintapp1
          image: arteiroacr.azurecr.io/blazorintapp1:latest
          imagePullPolicy: Always
          env: 
            - name: AZURE_OPENAI_API_URL 
              valueFrom: 
                secretKeyRef: 
                  name: azure-openai-url 
                  key: AZURE_OPENAI_API_URL 
            - name: AZURE_OPENAI_API_KEY
              valueFrom: 
                secretKeyRef: 
                  name: azure-openai-key 
                  key: AZURE_OPENAI_API_KEY 
          ports:
            - containerPort: 8080
