apiVersion: v1
kind: Service
metadata:
  name: blazorintapp1
  namespace: blazorintapp1
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: ClusterIP
  selector:
    app: blazorintapp1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
--
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blazorintapp1
  namespace: blazorintapp1
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - host: "blazorintapp1.azuretar.com"
    http:
      paths:
      - backend:
          service:
            name: blazorintapp1
            port:
              number: 8080
        path: /
        pathType: Prefix
              