apiVersion: v1
kind: Service
metadata:
  name: blazorintapp1
  namespace: blazorintapp1
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: blazorintapp1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
