apiVersion: v1
kind: Service
metadata:
  name: BlazorIntApp1
  namespace: blazorintapp1
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: BlazorIntApp1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080